
worldDirectory: E:/ZZTZips-extraction
indexDirectory: E:/tmp/zztsearchindex

museumDirectory: E:/tmp/zztsearchmuseumcatalog
museumUrlBase: https://museumofzzt.com/api/v1/

logging:
  level: INFO
  loggers:
    com.isaacbrodsky.zztsearch.web: DEBUG
